---
- name: Setup the homeserver
  hosts: all
  become: true

  tasks:
    - name: Update server and install essential packages
      ansible.builtin.include_tasks: tasks/essential.yml

    - name: Install docker
      ansible.builtin.include_tasks: tasks/docker.yml

    - name: Deploy docker apps
      ansible.builtin.include_tasks: "tasks/{{ item }}.yml"
      loop:
        - authelia
        - traefik
        - code_server
        - dashdot
        - duplicati
        - filebrowser
        - guacamole
        - heimdall
        - homarr
        - jellyfin
        - jellyseerr
        - monitoring
        - nextcloud
        - portainer
        - prowlarr
        - qbittorrent
        - radarr
        - sonarr
        - syncthing
        - unmanic
        - uptime_kuma
        - vaultwarden
        - watchtower
        - wireguard

    - name: Modify ownership of data and docker_apps directories
      ansible.builtin.include_tasks: tasks/add_ownership.yml

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Rebooting server to finish setup"

    - name: Check if traefik is working properly with authelia middleware
      ansible.builtin.uri:
        url: "https://wg.{{ domain }}"
        status_code:
          - 200
      register: traefik_authelia_check

    - name: Restart traefik container to ensure it can find authelia middleware
      community.docker.docker_container:
        name: traefik
        state: started
        restart: true
      when: traefik_authelia_check.status != 200
