---
- name: Add required permissions to data and docker_apps directories
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ data_dir }}"
    - "{{ docker_dir }}/code_server"
    - "{{ docker_dir }}/duplicati"
    - "{{ docker_dir }}/filebrowser"
    - "{{ docker_dir }}/guacamole"
    - "{{ docker_dir }}/heimdall"
    - "{{ docker_dir }}/jellyfin"
    - "{{ docker_dir }}/jellyseer"
    - "{{ docker_dir }}/monitoring"
    - "{{ docker_dir }}/nginx"
    - "{{ docker_dir }}/portainer"
    - "{{ docker_dir }}/prowlarr"
    - "{{ docker_dir }}/qbittorrent"
    - "{{ docker_dir }}/radarr"
    - "{{ docker_dir }}/sonarr"
    - "{{ docker_dir }}/syncthing"
    - "{{ docker_dir }}/unmanic"
    - "{{ docker_dir }}/uptime_kuma"
    - "{{ docker_dir }}/vaultwarden"
    - "{{ docker_dir }}/watchtower"
    - "{{ docker_dir }}/wireguard"
