---
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: safe
    autoremove: true

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Suppress login messages
  file:
    name: /home/{{ username }}/.hushlogin
    mode: 0644
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present