---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: safe
    autoremove: true

- name: Create Docker directory
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ data_dir }}"
    - "{{ data_dir }}/torrents"
    - "{{ data_dir }}/media"
    - "{{ data_dir }}/media/movies"
    - "{{ data_dir }}/media/tv"
    - "{{ data_dir }}/torrents/movies"
    - "{{ data_dir }}/torrents/tv"

- name: Create app directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ docker_dir }}/code_server"
    - "{{ docker_dir }}/duplicati"
    - "{{ docker_dir }}/filebrowser"
    - "{{ docker_dir }}/guacamole"
    - "{{ docker_dir }}/heimdall"
    - "{{ docker_dir }}/jellyfin"
    - "{{ docker_dir }}/jellyseer"
    - "{{ docker_dir }}/monitoring"
    - "{{ docker_dir }}/nginx"
    - "{{ docker_dir }}/portainer"
    - "{{ docker_dir }}/prowlarr"
    - "{{ docker_dir }}/qbittorrent"
    - "{{ docker_dir }}/radarr"
    - "{{ docker_dir }}/sonarr"
    - "{{ docker_dir }}/syncthing"
    - "{{ docker_dir }}/unmanic"
    - "{{ docker_dir }}/uptime_kuma"
    - "{{ docker_dir }}/vaultwarden"
    - "{{ docker_dir }}/watchtower"
    - "{{ docker_dir }}/wireguard"

- name: Suppress login messages
  ansible.builtin.file:
    name: /home/{{ username }}/.hushlogin
    mode: "0644"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists
