---
- name: Create filebrowser.db file
  ansible.builtin.file:
    path: "{{ docker_dir }}/filebrowser/filebrowser.db"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
    access_time: preserve
    modification_time: preserve

- name: Create file browser container
  community.docker.docker_container:
    name: filebrowser
    image: filebrowser/filebrowser
    env:
      PUID: "{{ username }}_uid"
      PGID: "{{ username }}_gid"
    pull: true
    state: started
    networks:
      - name: homelab
    ports:
      - "8081:80"
    volumes:
      - "/home/{{ username }}/:/srv"
      - "{{ docker_dir }}/filebrowser/:/data"
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges:true
