---
- name: Create heimdall container
  community.docker.docker_container:
    name: heimdall
    image: lscr.io/linuxserver/heimdall
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ username }}_uid"
      PGID: "{{ username }}_gid"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/heimdall/config:/config"
    networks:
      - name: homelab
