---
- name: Create jellyfin container
  community.docker.docker_container:
    name: jellyfin
    image: lscr.io/linuxserver/jellyfin
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ username }}_uid"
      PGID: "{{ username }}_gid"
      TZ: "{{ timezone }}"
      JELLYFIN_PublishedServerUrl: "{{ ansible_default_ipv4.address }}"
    volumes:
      - "{{ docker_dir }}/jellyfin/config:/config"
      - "{{ data_dir }}/media:/data/media"
    networks:
      - name: homelab
