---
- name: Create nginx proxy manager container
  community.docker.docker_container:
    name: nginx_proxy_manager
    image: jc21/nginx-proxy-manager:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    networks:
      - name: homelab
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "{{ docker_dir }}/nginx/data:/data"
      - "{{ docker_dir }}/nginx/letsencrypt:/etc/letsencrypt"
