---
- name: Create nginx proxy manager container
  community.docker.docker_container:
    name: nginx proxy manager
    image: jc21/nginx-proxy-manager:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "{{ docker_dir }}/nginx/config:/config"
      - "{{ docker_dir }}/nginx/letsencrypt:/etc/letsencrypt"