---
- name: Create prowlarr container
  community.docker.docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ username }}_uid"
      PGID: "{{ username }}_gid"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/prowlarr/config:/config"
    networks:
      - name: homelab
