---
- name: Get latest release of vuetorrent
  ansible.builtin.uri:
    url: https://api.github.com/repos/WDaan/VueTorrent/releases/latest
    return_content: true
  register: latest_release

- name: Download vuetorrent
  ansible.builtin.get_url:
    url: "{{ latest_release.json.zipball_url }}"
    dest: "{{ docker_dir }}/qbittorrent/vuetorrent.zip"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Unzip vuetorrent
  ansible.builtin.unarchive:
    src: "{{ docker_dir }}/qbittorrent/vuetorrent.zip"
    dest: "{{ docker_dir }}/qbittorrent"
    remote_src: true
    creates: "{{ docker_dir }}/qbittorrent/vuetorrent"

- name: Create qbittorrent container
  community.docker.docker_container:
    name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      WEBUI_PORT: 8080
    volumes:
      - "{{ docker_dir }}/qbittorrent/config:/config"
      - "{{ data_dir }}/torrents:/data/torrents"
      - "{{ docker_dir }}/qbittorrent/vuetorrent:/vuetorrent"
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
