---
- name: Create radarr container
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ username }}_uid"
      PGID: "{{ username }}_gid"
      TZ: "{{ timezone }}"
      DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
    volumes:
      - "{{ docker_dir }}/radarr/config:/config"
      - "{{ data_dir }}:/data"
    networks:
      - name: homelab
