---
- name: Create sonarr container
  community.docker.docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr
    pull: true
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ username }}_uid"
      PGID: "{{ username }}_gid"
      TZ: "{{ timezone }}"
      DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
    volumes:
      - "{{ docker_dir }}/sonarr/config:/config"
      - "{{ data_dir }}:/data"
    networks:
      - name: homelab
