---
username: vagrant

docker_dir: /home/{{ username }}/docker_apps
data_dir: /home/{{ username }}/data

ip_address: 192.168.60.4

puid: 1000

pgid: 1000

timezone: Asia/Kolkata

wg_password: wg_password

codeserver_password: codeserver_password

packages:
  - unzip
  - wget
  - curl
  - git
  - ranger
  - htop
  - speedtest-cli
  - build-essential
  - neovim
  - nano
  - python3
  - python3-pip

docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools
  - docker-compose

docker_packages:
  - docker-ce
  - docker-compose
  - cgroupfs-mount

docker_apps:
  - code_server
  - duplicati
  - filebrowser
  - guacamole
  - heimdall
  - jellyfin
  - jellyseer
  - monitoring
  - nginx
  - portainer
  - prowlarr
  - qbittorrent
  - radarr
  - sonarr
  - syncthing
  - unmanic
  - uptime_kuma
  - vaultwarden
  - watchtower
  - wireguard
