---
username: root

docker_dir: /home/{{ username }}/docker_apps
data_dir: /home/{{ username }}/data

ip_address: 172.105.34.67

puid: "0"

pgid: "0"

timezone: Asia/Kolkata

wg_password: wg_password

codeserver_password: codeserver_password

packages:
  - unzip
  - wget
  - curl
  - git
  - htop
  - speedtest-cli
  - neovim
  - nano
  - python3
  - python3-pip

pip_packages:
  - ansible
  - github3.py
  - docker

docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
